---
name: Rust source coverage
description: Docker github action that runs cargo test while gathering source-based coverage data
branding:
  icon: play-circle
  color: black
runs:
  using: 'docker'
  image: 'Dockerfile'
