---
name: Rust source coverage
description: Docker github action that runs cargo test while gathering source-based coverage data
branding:
  icon: play-circle
  color: black
inputs:
  dependencies_debian:
    description: 'Dependencies as Debian packages to install; used if defined'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
